mapalus/protected/modules/mailbox/models/News.php
<?php

/**
 * This is the model class for table "{{mailbox_conversation}}".
 *
 * The followings are the available columns in table '{{mailbox_conversation}}':
 * @property string $conversation_id
 * @property integer $initiator_id
 * @property integer $interlocutor_id
 * @property string $subject
 * @property integer $bm_read
 * @property integer $bm_deleted
 * @property string $modified
 * @property string $is_system
 */
class News extends Mailbox
{

	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function isNew($userid)
	{
		/*
		 * If your database keeps track of user logins date/time you could rewrite
		* this method to return true if the modified timestamp is greater than
		* (ie. more recent) the user's previous login timestamp (ie the last time
				* the user successfully logged-in, not counting the current login).
		*/
		/*
		 if($this->modified > Yii::app()->user->previousLogin )
			return true;
		return false;
		*/

		// for now we just use a static time limit...
		if($this->modified > time() - 3600 * 24 * 7)
			return true;
		return false;
	}

	public function delete()
	{
		return $this->destroy();
	}

}

mapalus/protected/modules/mailbox/controllers/NewsController.php
<?php


class NewsController extends Controller
{
	public $layout='//layouts/main2';

	public $buttons = array('admin'=>array('delete'=>'deleted'));


	public function filters()
	{
		if($this->module->authManager=='rights') {
			return array(
					'rights', // perform access control for CRUD operations
			);
		}
		else return array();
	}

	public function behaviors()
	{
		return array(
				'ButtonAction'=>array(
						'class'=>'mailbox.behaviors.ButtonActionBehavior',
						'controller'=>$this,
						'module'=>$this->module,
						'buttons'=>$this->buttons,
						'arclass'=>'News',
				)
		);
	}

	public function actionIndex($ajax=null)
	{
		if($this->module->isAdmin() && isset($_POST['convs']))
		{
			$this->buttonAction('index','admin');
		}
		$this->module->registerConfig($this->getAction()->getId());
		$dataProvider = new CActiveDataProvider( News::model()->inbox($this->module->newsUserId) );
		if(isset($ajax))
			$this->renderPartial('_news',array('dataProvider'=>$dataProvider));
		else{
			if(!isset($_GET['Mailbox_sort']))
				$_GET['Mailbox_sort'] = 'modified.desc';
				
			$this->render('news',array('dataProvider'=>$dataProvider));
		}
	}



	public function actionInfo($id)
	{
		//		$cs =& $this->module->getClientScript();
		//		$cs->registerScriptFile($this->module->getAssetsUrl().'/js/message.js');
		//		$js = '$(".mailbox-message-list").yiiMailboxMessage('.$this->module->getOptions().");";
		//		$cs->registerScript('mailbox-js',$js,CClientScript::POS_READY);

		$conv = Mailbox::conversation($id);

		$reply = new Message;
		$this->render('info',array('conv'=>$conv, 'reply'=>$reply));

	}

}

mapalus/protected/modules/mailbox/views/news/_news_list.php
<?php

//CVarDumper::dump($data); return;

$userid =& $this->module->getUserId();


$viewLink = $this->createUrl('news/info',array('id'=>$data->conversation_id));
//$deleteLink = $this->createUrl('message/delete',array('id'=>$data->conversation_id));


$received = $this->module->getDate($data->modified);
$itemCssClass = $data->isNew($userid)? 'msg-new' : 'msg-read';

$status = "View this news update";
?>
<tr
	class="mailbox-item <?php echo $itemCssClass; ?> <?php if($this->getAction()->getId()!='sent') echo 'mailbox-draggable-row'; ?>">
	<?php if(false): // add dragdrop handle ?>
	<td width="25"><div class="mailbox-item-wrapper mailbox-drag">&nbsp;</div>
	</td>
	<?php endif; ?>

	<?php if( $this->module->isAdmin() ) : ?>
	<td width="25"><label class="ui-helper-reset"
		for="conv_<?php echo $data->conversation_id; ?>">
			<div class="mailbox-item-wrapper mailbox-check">
				<input class="mailbox-check "
					id="conv_<?php echo $data->conversation_id; ?>" type="checkbox"
					name="convs[]" value="<?php echo $data->conversation_id; ?>" />
			</div>
	</label>
	</td>
	<?php endif; ?>
	<td class="mailbox-subject-brief">
		<div class="mailbox-item-wrapper mailbox-subject mailbox-ellipsis">
			<span class="mailbox-subject-text"><a class="mailbox-link"
				title="<?php echo $status; ?>" href="<?php echo $viewLink; ?>"><?php echo preg_replace('/[\s]+/','&nbsp;',(($data->subject)? $data->subject : $this->module->defaultSubject)); ?>
			</a> </span><span class="mailbox-msg-brief">&nbsp;-&nbsp;<?php echo preg_replace('/[\s]+/','&nbsp;',substr($data->text,0,50)); ?>
			</span>
		</div>
	</td>
	<td class="mailbox-received">
		<div align="right" class="mailbox-item-wrapper mailbox-ellipsis">
			<?php if($data->is_replied) : ?>
			<div class="mailbox-replied" title="this message has been replied to"></div>
			<?php endif; ?>
			<?php echo $received; ?>
		</div>

	</td>
</tr>

mapalus/protected/modules/mailbox/views/news/info.php
<?php
$this->breadcrumbs=array(
		'Site News'=>array('news/'),
		'News Update',
);

?>
<div class="mailbox-news-story">


	<?php
	foreach(Yii::app()->user->getFlashes() as $key => $message) {
		echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
	}
	?>
	<div class="mailbox-message-subject">
		<?php echo ($conv->subject)? $conv->subject : $this->module->defaultSubject; ?>
	</div>

	<br />
	<?php
	$first_message=1;
	foreach($conv->messages as $msg):
	$sender = $this->module->getUserName($msg->sender_id);
	if(!$sender)
		$sender = $this->module->deletedUser;
	?>

	<div class="mailbox-message-text">
		<?php echo $msg->text; ?>
	</div>



	<div class="mailbox-message-header">
		<div class="message-sender">
			<?php	echo 'Author: ' . ucfirst($sender); ?>
		</div>
		<div class="message-date">
			Last Updated:
			<?php echo date("Y-m-d H:i a",$msg->created); ?>
		</div>
		<br />
	</div>

	<br />
	<?php $first_message=0;
	endforeach;

	if($this->module->authManager)
		$authReply = Yii::app()->user->checkAccess("Mailbox.Message.Reply");
	else
		$authReply = $this->module->sendMsgs;
?>
</div>

mapalus/protected/modules/mailbox/views/news/news.php
<?php

if($this->getAction()->getId()!='index')
	$this->breadcrumbs=array(
			ucfirst($this->module->id)=>array('news/'),
			ucfirst($this->getAction()->getId())
	);
else
	$this->breadcrumbs=array('Site News');

//$this->renderpartial('_menu');

if(isset($_GET['Mailbox_sort']))
	$sortby = $_GET['Mailbox_sort'];
else
	$sortby = '';

echo '<div class="news-list ui-helper-clearfix" sortby="'.$sortby.'">';

$this->renderpartial('../message/_flash');

if($dataProvider->getItemCount() > 0) {
	?>
<h1>Site News</h1>
<form id="message-list-form"
	action="<?php echo $this->createUrl($this->getId().'/'.$this->getAction()->getId()); ?>"
	method="post">
	<div class="mailbox-clistview-container ui-helper-clearfix">
		<?php
		if($this->module->isAdmin() && $dataProvider->getItemCount() > 1) : ?>
		<div class="btn-group mailbox-checkall-buttons">
			<button class="checkall" />
			Check All
			</button>
			<button class="uncheckall" />
			Uncheck All
			</button>
		</div>
		<?php
		endif;

		$this->widget('zii.widgets.CListView', array(
				'id'=>'mailbox',
				'dataProvider'=>$dataProvider,
				'itemView'=>'_news_list',
				'itemsTagName'=>'table',
				'template'=>'<div class="mailbox-summary">{summary}</div>{sorter}<div id="mailbox-items" class="ui-helper-clearfix">{items}</div>{pager}',
				'sortableAttributes'=>array('modified'=>'News Date'),
				'loadingCssClass'=>'mailbox-loading',
				'ajaxUpdate'=>'mailbox-list',
				'afterAjaxUpdate'=>'$.yiimailbox.updateMailbox',
				'emptyText'=>'<div style="width:100%"><h3>No news to report.</h3></div>',
				//'htmlOptions'=>array('class'=>'ui-helper-clearfix'),
				'sorterHeader'=>'',
				'sorterCssClass'=>'mailbox-sorter',
				'itemsCssClass'=>'mailbox-items-tbl ui-helper-clearfix',
				'pagerCssClass'=>'mailbox-pager',
				//'updateSelector'=>'.inbox',
		));
		?>
		<?php if($this->module->isAdmin()) : ?>
		<div style="clear: left">
			<span class="mailbox-buttons-label">With selected:</span> <input
				type="submit" id="mailbox-action-delete" class="btn mailbox-button"
				name="button[delete]" value="delete" />

		</div>
		<?php endif; ?>
	</div>
</form>

<?php

}
else {
	echo '<div class="mailbox-empty">No news to report.</div>';
}

echo '</div>';

?>